/// Flutter icons MyFlutterApp
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData brightness_5 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData account_circle = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData account_box = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData add_box = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData add_circle = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData more_horiz = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData add_shopping_cart = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData adjust = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData alarm = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData archive = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData block = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData build = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData check = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData check_circle = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData content_cut = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData delete = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData done = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData done_all = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData favorite = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData favorite_border = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData fingerprint = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData format_color_fill = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData healing = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData group = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData gradient = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData help_outline = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData help = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData import_export = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData info = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData info_outline = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData language = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData local_drink = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData local_laundry_service = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData local_offer = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData local_phone = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData local_shipping = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData map = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData mail_outline = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData monetization_on = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData money_off = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData place = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData pin_drop = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData priority_high = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData tune = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData trash_empty = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData credit_card = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData droplet = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData water = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData air = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData dot_3 = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData cog_outline = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData cog = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData hourglass = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData clock = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData cog_1 = const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData cog_circled = const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData cog_2 = const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData cogs = const IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData wrench = const IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData wrench_circled = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData calendar_circled = const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData more_vert = const IconData(0xe841, fontFamily: _kFontFam);
  static const IconData coatrack = const IconData(0xe842, fontFamily: _kFontFam);
  static const IconData image2vector__3_ = const IconData(0xe843, fontFamily: _kFontFam);
  static const IconData minus = const IconData(0xe844, fontFamily: _kFontFam);
  static const IconData minus_outline = const IconData(0xe845, fontFamily: _kFontFam);
  static const IconData shoe = const IconData(0xe846, fontFamily: _kFontFam);
  static const IconData polo = const IconData(0xe847, fontFamily: _kFontFam);
  static const IconData tshirt = const IconData(0xe848, fontFamily: _kFontFam);
  static const IconData shirt_1 = const IconData(0xe849, fontFamily: _kFontFam);
  static const IconData pants = const IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData hoodie = const IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData high_heels = const IconData(0xe84c, fontFamily: _kFontFam);
  static const IconData dress = const IconData(0xe84d, fontFamily: _kFontFam);
  static const IconData suit = const IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData shirt = const IconData(0xe84f, fontFamily: _kFontFam);
  static const IconData cap = const IconData(0xe850, fontFamily: _kFontFam);
  static const IconData sleeveless = const IconData(0xe851, fontFamily: _kFontFam);
  static const IconData skirt = const IconData(0xe852, fontFamily: _kFontFam);
  static const IconData shorts = const IconData(0xe853, fontFamily: _kFontFam);
  static const IconData slippers = const IconData(0xe854, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xf061, fontFamily: _kFontFam);
  static const IconData trash_2 = const IconData(0xf083, fontFamily: _kFontFam);
  static const IconData trash_1 = const IconData(0xf1f8, fontFamily: _kFontFam);
}
