name: wash_x
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.6.6
  flutter_facebook_login: ^1.1.1
  google_sign_in: ^3.0.4
  local_auth: ^0.2.1
  cloud_firestore: ^0.8.0
  flutter_twitter_login: ^1.1.0
  image_picker: ^0.4.6
  firebase_remote_config: ^0.0.5
  firebase_core: ^0.2.5
  scoped_model: ^0.3.0
  #speech_recognition: ^0.2.0+1
  shared_preferences: ^0.4.2
  flutter_tts: ^0.0.7
  #flutter_dialogflow: ^0.0.1
  simple_permissions: ^0.1.8
  crashlytics: ^0.0.2
  firebase_analytics: ^1.0.3
  firebase_performance: ^0.0.5
  firebase_storage: ^1.0.4
  cached_network_image: ^0.4.1
  #camera: ^0.2.4
  path_provider: ^0.4.1
  video_player: ^0.5.2
  image: ^2.0.4
  rounded_modal: ^1.0.0
  groovin_widgets: ^1.1.0
  percent_indicator: ^1.0.10
  uuid: ^1.0.3
  camera:
    git:
      url: https://github.com/maral/plugins.git
      path: packages/camera


  


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - images/ic_basket.png
    - images/ic_facebook.png
    - images/ic_qr_code.png
    - images/ic_link_share.png
    - images/ic_question.png
    - images/wash_t_1.png
    - images/wash_t_2.png
    - images/wash_t_3.png
    - images/wash_t_4.png
    - images/wash_t_5.png
    - images/wash_t_6.png
    - images/wash_t_7.png
  #  - images/a_dot_ham.jpeg

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/myflutterapp.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
